# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-25 08:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u90e8\u95e8',
                'verbose_name_plural': '\u7528\u6237\u90e8\u95e8',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe5\x90\x8d\xe7\xa7\xb0')),
                ('user', models.CharField(blank=True, max_length=64, null=True, verbose_name='API\u9a8c\u8bc1\u7528\u6237')),
                ('token', models.CharField(blank=True, max_length=128, null=True, verbose_name='API token')),
                ('create_url', models.CharField(max_length=255, verbose_name='\u7528\u6237\u6388\u6743API')),
                ('delete_url', models.CharField(max_length=255, verbose_name='\u7528\u6237\u56de\u6536API')),
            ],
            options={
                'verbose_name': '\u6388\u6743',
                'verbose_name_plural': '\u6388\u6743',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, verbose_name=b'\xe9\x82\xae\xe7\xae\xb1\xe5\x9c\xb0\xe5\x9d\x80')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u542f\u7528')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7ba1\u7406\u5458')),
                ('username', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='\u8d26\u6237')),
                ('nickname', models.CharField(max_length=64, null=True, verbose_name='\u59d3\u540d')),
                ('token', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='token')),
                ('sex', models.CharField(choices=[('\u5973', '\u5973'), ('\u7537', '\u7537')], default=0, max_length=2, null=True, verbose_name='\u6027\u522b')),
                ('tel', models.CharField(blank=True, default=None, max_length=32, null=True, validators=[django.core.validators.RegexValidator(b'^\\d{0,9}$')], verbose_name='\u5ea7\u673a')),
                ('rtx_num', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='RTX\u8d26\u53f7')),
                ('phone', models.CharField(blank=True, default=None, max_length=11, null=True, validators=[django.core.validators.RegexValidator(b'^\\d{0,9}$')], verbose_name='\u624b\u673a')),
                ('uid', models.IntegerField(blank=True, null=True, verbose_name='UID')),
                ('memo', models.TextField(blank=True, default=None, null=True, verbose_name='\u5907\u6ce8')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('valid_begin_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6709\u6548\u671f\u5f00\u59cb\u65f6\u95f4')),
                ('valid_end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u6709\u6548\u671f\u7ed3\u675f\u65f6\u95f4')),
                ('allowable', models.ManyToManyField(blank=True, related_name='allowable_permission', to='UsersControl.Permission', verbose_name=b'\xe5\x85\x81\xe8\xae\xb8\xe6\x9d\x83\xe9\x99\x90')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UsersControl.Department', verbose_name='\u90e8\u95e8')),
                ('prohibited', models.ManyToManyField(blank=True, related_name='prohibited_permission', to='UsersControl.Permission', verbose_name=b'\xe7\xa6\x81\xe6\xad\xa2\xe6\x9d\x83\xe9\x99\x90')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='permission',
            field=models.ManyToManyField(blank=True, to='UsersControl.Permission', verbose_name=b'\xe5\x8f\xaf\xe7\x99\xbb\xe9\x99\x86\xe7\xb3\xbb\xe7\xbb\x9f'),
        ),
    ]
