# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-25 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandlesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='\u7528\u6237')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u65f6\u95f4')),
                ('log_type', models.CharField(choices=[('\u521b\u5efa\u7528\u6237', '\u521b\u5efa\u7528\u6237'), ('\u5220\u9664\u7528\u6237', '\u5220\u9664\u7528\u6237'), ('\u4fee\u6539\u5bc6\u7801', '\u4fee\u6539\u5bc6\u7801'), ('\u4fee\u6539\u6743\u9650', '\u4fee\u6539\u6743\u9650')], max_length=24, verbose_name='\u65e5\u5fd7\u7c7b\u578b')),
                ('source', models.CharField(max_length=64, verbose_name='\u65e5\u5fd7\u6765\u6e90')),
                ('detail', models.TextField(verbose_name='\u8be6\u7ec6\u65e5\u5fd7')),
                ('component', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e8b\u4ef6\u5b50\u9879')),
            ],
        ),
    ]
