# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-28 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handleslog',
            options={'verbose_name': '\u65e5\u5fd7\u4fe1\u606f', 'verbose_name_plural': '\u65e5\u5fd7\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='handleslog',
            name='log_type',
            field=models.CharField(choices=[('\u521b\u5efa\u7528\u6237', '\u521b\u5efa\u7528\u6237'), ('\u4fee\u6539\u7528\u6237', '\u4fee\u6539\u7528\u6237'), ('\u5220\u9664\u7528\u6237', '\u5220\u9664\u7528\u6237'), ('\u521b\u5efa\u6743\u9650\u7cfb\u7edf', '\u521b\u5efa\u6743\u9650\u7cfb\u7edf'), ('\u4fee\u6539\u6743\u9650\u7cfb\u7edf', '\u4fee\u6539\u6743\u9650\u7cfb\u7edf'), ('\u5220\u9664\u6743\u9650\u7cfb\u7edf', '\u5220\u9664\u6743\u9650\u7cfb\u7edf'), ('\u521b\u5efa\u90e8\u95e8', '\u521b\u5efa\u90e8\u95e8'), ('\u4fee\u6539\u90e8\u95e8', '\u4fee\u6539\u90e8\u95e8'), ('\u5220\u9664\u90e8\u95e8', '\u5220\u9664\u90e8\u95e8'), ('\u4fee\u6539\u5bc6\u7801', '\u4fee\u6539\u5bc6\u7801'), ('\u4fee\u6539\u6743\u9650', '\u4fee\u6539\u6743\u9650')], max_length=24, verbose_name='\u65e5\u5fd7\u7c7b\u578b'),
        ),
    ]
